---
title: "beta-PIE testing"
author: "Dan McGlinn"
date: "1/18/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mobsim)
library(mobr)

S_pool = 100
N = 1000

# run across a more even and less even SAD
cv_abund = list(list(cv_abund=1), list(cv_abund=5))

# generate maps
maps = NULL
maps$agg = lapply(cv_abund, function(x) 
                  sim_thomas_community(S_pool, N, 'lnorm', x, fix_s_sim = T))
maps$poi = lapply(cv_abund, function(x) 
                  sim_poisson_community(S_pool, N, 'lnorm', x, fix_s_sim = T))
```

```{r}
# output maps
#maps of the four treatments
par(mfrow=c(2,2))
for(i in seq_along(cv_abund)) {
    plot(maps$agg[[i]], axes=F, xlab='', ylab='', 
         main='Aggregated treatment')
    plot(maps$poi[[i]], axes=F, xlab='', ylab='', 
         main='Random treatment')
}
```


```{r}
# sample n_quadrats from the mapped communities
n_quadrats = 10

comms = lapply(maps, function(x) 
               lapply(x, function(y) 
                      sample_quadrats(y, n_quadrats, plot = F)))
```

```{r}
# aggregate comms data into a community and attributes dataframes

spdat = rbind(dplyr::bind_rows(lapply(comms$agg, function(x) x$spec_dat)),
              dplyr::bind_rows(lapply(comms$poi, function(x) x$spec_dat)))

coords = rbind(dplyr::bind_rows(lapply(comms$agg, function(x) x$xy_dat)),
               dplyr::bind_rows(lapply(comms$poi, function(x) x$xy_dat)))

plot_attr = data.frame(coords, 
                       spatial = rep(c('agg', 'poi'), 
                                     each= n_quadrats * length(cv_abund)),
                       SAD_CV = rep(rep(unlist(cv_abund), 
                                    each= n_quadrats), 2))
plot_attr$group = paste(plot_attr$spatial, plot_attr$SAD_CV, sep='_')

sim_mob_in = make_mob_in(spdat, plot_attr) 
```

```{r}
# compute stats
mob_stats = get_mob_stats(sim_mob_in, 'group')

plot(mob_stats)
```
